### ISSUE TITLE
请问用医学数据finetuning了之后会遗忘其他领域的对话能力吗

### ISSUE THREAD

**Issue by lyx3911** [xionghonglin/DoctorGLM#19]

**Comment by xionghonglin** [comment]
在使用官方的ptuningv2时发生遗忘的情况还是比较少的。此外，可以在训练数据里添加prompt如‘你现在是一个医生，请回答以下患者的问题’等方式改善模型遗忘的情况。

**Comment by KaishuaiXu** [comment]
> 

fine-tune后回复出现词语不断重复，不管训练多少个step都这样。这是什么情况？GPT-2和BART都不会出现这种问题了。
