### ISSUE TITLE
可以共享一下那个微调的BART模型吗？

### ISSUE THREAD

**Issue by Youfenghao** [xionghonglin/DoctorGLM#26]

**Comment by zhaozh10** [comment]
很抱歉回复较晚，微调过后的BART模型位于[medical_chat-en-zh](https://huggingface.co/zhaozh/medical_chat-en-zh)，用于将英文的医学对话翻译为中文。在另一个同步进行的工作中，我们还针对MIMIC-CXR数据集的胸片报告进行了微调，可用于将MIMIC-CXR数据集的胸片报告翻译为中文，模型位于[radiology-report-en-zh](https://huggingface.co/zhaozh/radiology-report-en-zh-ft-base)，同样基于DoctorGLM论文中所使用的方法进行微调

**Comment by Youfenghao** [comment]
已收到，非常感谢 @zhaozh10
