### ISSUE TITLE
训练时间

### ISSUE THREAD

**Issue by FrankWhh** [xionghonglin/DoctorGLM#5]
readme里列出来的数据量很大，请问你们训了多久，几个epoch

**Comment by zhaozh10** [comment]
目前仅在Chinese Medical Dialogue数据集上进行了微调，在A100 80G上训练了1个epoch（8小时）。
加入新数据集的微调结果会在后续更新

**Comment by FrankWhh** [comment]
这个数据集我看有3.4M条，8h就能跑完一个epoch！我用A100跑个1M的数据集，显示要近90h。所以你们训练的参数能列一下吗？max_length, r, batch_size啥的

**Comment by zhaozh10** [comment]
首先，我们表格的排版似乎出了些问题，CMD数据集是1.9M个样本。训练过程中使用的超参数如下：BatchSize=4,采用lion optimizer, max_sequence_length=512。LoRA模块设置Rank=8。更多内容可以参考我们的论文[DoctorGLM](https://arxiv.org/abs/2304.01097)
